version: '3'
services:
        mosquitto:
                image: eclipse-mosquitto
                ports:
                        - "1883:1883"
                        - "9001:9001"
        nodered:
                build: ./nodered
                ports:
                        - "80:1880"
                volumes:
                        - data:/data
        influxdb:
                image: influxdb
                ports:
                        - "8086:8086"
                volumes:
                        - influxdb:/var/lib/influxdb
        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
volumes:
        data:
        influxdb:
